---
title: "Descriptives for model cohort"
subtitle: "Cohort Definition"
author: "Xilin Chen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  comment = NA,
  message = FALSE,
  warning = FALSE,
  R.options = list(width = 220),
  dev.args = list(bg = 'transparent'),
  dev = 'png',
  layout = "l-body-outset",
  fig.align = 'center',
  out.width = '75%',
  fig.asp = .75,
  fig.pos = 'H',
  cache = FALSE, 
  cache.rebuild = TRUE
)

library(tidyverse)
library(gtsummary)
library(kableExtra)
library(patchwork)
library(flextable)
```

```{r}
# load data
load("/Volumes/George_Surgeon_Projects/MOC_vs_Outcome/data/medicare_abs_model_ready_no_na.rdata")

covariates = c(
  # choose one cert status--
  # 're_cert_status',
  're_cert_bin',
  # other--
  'flg_male',
  'age_at_admit',
  'AHRQ_score',
  'race_white',
  'ses',
  'emergent_admit',
  'year',
  'surgeon_yearly_load',
  'years_after_initial_certification',
  "had_assist_surg",
  # hospital--
  'hospital_urban',
  'hospital_beds_gt_350',
  'val_hosp_rn2inptday_ratio',
  'val_hosp_mcday2inptday_ratio'
)

```


## Table1


### Surgeon level

```{r}
# not using surgeon volume as covariate based on ECV project's discussion 
# medicare_abs_model_ready_no_na %>% 
#   distinct(npi, re_cert_bin, surgeon_yearly_load) %>% 
#   group_by(npi) %>% 
#   mutate(mean_yearly_case_per_sug = mean(surgeon_yearly_load)) %>% 
#   ungroup() %>% 
#   distinct(npi, re_cert_bin, mean_yearly_case_per_sug) %>% 
#   select(-npi) %>% 
#   tbl_summary(by = re_cert_bin) %>% 
#   add_p()


medicare_abs_model_ready_no_na %>%
  distinct(npi, re_cert_bin) %>%
  count(re_cert_bin, name = "n of surgeons") %>% 
  kable() %>% 
  kable_styling(full_width = F)
```


Complete cases

### Case level

```{r}
medicare_abs_model_ready_no_na %>% 
  select(!!covariates) %>% 
  tbl_summary(by = re_cert_bin) %>% 
  add_p() %>% 
  as_flex_table()
  
```

<!-- ### 162 procedures procedures -->

<!-- ```{r} -->
<!-- medicare_abs_model_ready_no_na %>%  -->
<!--   count(procedure) %>%  -->
<!--   mutate(perc = round(n/sum(n), 2), -->
<!--          percentage = scales::percent(perc)) %>%  -->
<!--   select(-perc) %>%  -->
<!--   arrange(-n) %>%  -->
<!--   rename("n cases" = n) %>%  -->
<!--   slice(1:10) %>% -->
<!--   kable() %>% -->
<!--   kable_styling(full_width = F) -->

<!-- write_csv(procedure_list, file = "data/procedure_list.csv") -->
<!-- ``` -->

