---
title: "Model Results using CORE procedures"
author: "Xilin Chen"
date: "`r Sys.Date()`"
output: 
  html_document:
        toc: yes
        toc_depth: 4
        toc_float:
          toc_collapsed: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,                                     # code
  message = F,
  warning = F,
  error = F,
  comment = NA,
  R.options = list(width = 220),
  dev.args = list(bg = 'transparent'),          # viz
  fig.align = 'center',
  cache = F
)
library(tidyverse)
library(glmmTMB)
library(marginaleffects)
library(emmeans)
library(kableExtra)
```

```{r}
#load models
load("/Volumes/George_Surgeon_Projects/MOC_vs_Outcome/model/core_proc/death_model_bin.rdata")
load("/Volumes/George_Surgeon_Projects/MOC_vs_Outcome/model/core_proc/cmp_model_bin.rdata")
```


## Death

### Model summary

```{r}
summary(death_model_bin)
```

### marginal means

```{r}
death_means = emmeans(death_model_bin, "re_cert_bin",  type = "response", data = death_model_bin$frame, weights = "cells")

plot(death_means) +
  scale_x_continuous(labels = scales::percent_format()) +
  labs(y = "",
       title = "risk-adjusted rates") +
  medicareAnalytics::theme_cstar()

```


## Severe Complication

```{r}
summary(cmp_model_bin)
```

```{r}
cmp_means = emmeans(cmp_model_bin, "re_cert_bin",  type = "response", data = cmp_model_bin$frame,  weights = "cells")

plot(cmp_means) +
  scale_x_continuous(labels = scales::percent_format()) +
  labs(y = "",
       title = "risk-adjusted rates") +
  medicareAnalytics::theme_cstar()
```

## Certification 3 categories

Recorded Failed, No record, passed.

Purpose: to see if there is a significant differences between  no record vs. failed surgeons.

```{r}
load("/Volumes/George_Surgeon_Projects/MOC_vs_Outcome/model/core_proc/cmp_model_bin_3_cert_cat.rdata")
load("/Volumes/George_Surgeon_Projects/MOC_vs_Outcome/model/core_proc/death_model_bin_3_cert_cat.rdata")
```

### Death

```{r}
# summary(death_model_bin)
broom.mixed::tidy(death_model_bin) %>% 
  mutate_if(is.numeric, ~round(.x,2)) %>% 
  select(-component) %>% 
  kable() %>% 
  kable_styling(full_width = F) 
```

### Complication

```{r}
# summary(cmp_model_bin)
broom.mixed::tidy(cmp_model_bin) %>% 
  mutate_if(is.numeric, ~round(.x,2)) %>% 
  select(-component) %>% 
  kable() %>% 
  kable_styling(full_width = F) 
```



