---
title: "Descriptives for model cohort"
subtitle: "Cohort Definition"
author: "Xilin Chen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  comment = NA,
  message = FALSE,
  warning = FALSE,
  R.options = list(width = 220),
  dev.args = list(bg = 'transparent'),
  dev = 'png',
  layout = "l-body-outset",
  fig.align = 'center',
  out.width = '75%',
  fig.asp = .75,
  fig.pos = 'H',
  cache = FALSE, 
  cache.rebuild = TRUE
)

library(tidyverse)
library(gtsummary)
library(kableExtra)
library(patchwork)
```

```{r}
# load data
load("/Volumes/George_Surgeon_Projects/MOC_vs_Outcome/data/medicare_abs_model_ready_no_na.rdata")

covariates = c(
  # choose one cert status--
  # 're_cert_status',
  're_cert_bin',
  # other--
  'flg_male',
  'age_at_admit',
  'AHRQ_score',
  'race_white',
  'ses',
  'emergent_admit',
  'year',
  'surgeon_yearly_load',
  # 'years_after_initial_certification',
  "had_assist_surg"
  # hospital--
  # 'hospital_icu',
  # 'hospital_urban',
  # 'hospital_beds_gt_350',
  # 'hospital_icu',
  # 'hospital_rn2bed_ratio',
  # 'hospital_mcday2inptday_ratio'
)

```


## Table1

### Case level

```{r}
medicare_abs_model_ready_no_na %>% 
  select(!!covariates, -year, - surgeon_yearly_load) %>% 
  tbl_summary(by = re_cert_bin) %>% 
  add_p()
```

### Surgeon level

```{r}
medicare_abs_model_ready_no_na %>% 
  distinct(npi, re_cert_bin, surgeon_yearly_load) %>% 
  select(-npi) %>% 
  tbl_summary(by = re_cert_bin) %>% 
  add_p()
```

### By top 10 procedures

```{r}
medicare_abs_model_ready_no_na %>% 
  count(procedure) %>% 
  mutate(perc = round(n/sum(n), 2),
         percentage = scales::percent(perc)) %>% 
  select(-perc) %>% 
  arrange(-n) %>% 
  slice(1:10) %>% 
  kable() %>% 
  kable_styling(full_width = F)
```

